### ISSUE TITLE
Running without install step (aka "config on the command line")

### ISSUE THREAD

**Issue by holtgrewe** [dantaki/SV2#10]
First of all, thanks for this great tool!

In my setting, the current way of installing the data and the path to the reference is somewhat problematic. We have central installation of reference sequences and databases (e.g., SV2's persisted classifier model) which is managed independently from installing software.

I would prefer a way to specify the path to the reference and the downloaded data on the command line when calling `sv2` for re-genotyping reads.

Would this be possible?

**Comment by dantaki** [comment]
I'm not sure if I fully understand your question. SV2 should provide an option to download the resource files to a different location (with `sv2 -download`) 

```
$ sv2 -download

sv2 version:1.4.3    report bugs to <dantaki at ucsd dot edu>       error messages located in STDOUT
Install sv2 resource files to the default location? < /usr/lib/python2.7/site-packages/sv2/resources/ > [Y/n] 

$ n

Enter sv2 resource file destination:

$ /home/atreus/ref/ # note tab completion is not available here

sv2 resource files will require 238M of free space in /home/atreus/ref/. Proceed with installation? [Y/n] 

$ Y

100% [......................................................................] 249267490 / 249267490 INSTALL COMPLETE
Run < sv2 -hg19 FASTA [-hg38,-mm10] > to configure sv2

$ ]$ ls /home/atreus/ref/*

/home/atreus/ref/hg19_excluded.bed.gz
/home/atreus/ref/hg19.genome
/home/atreus/ref/hg38_excluded.bed.gz
/home/atreus/ref/hg38.genome
/home/atreus/ref/mm10_excluded.bed.gz
/home/atreus/ref/mm10.genome
/home/atreus/ref/par_hg19.bed
/home/atreus/ref/par_hg38.bed
/home/atreus/ref/par_mm10.bed

/home/atreus/ref/annotation_files:
hg19_1000Genomes_DEL.bed  hg19_genes.bed.gz         hg38_cytoband.bed         mm10_cytoband.bed
hg19_1000Genomes_DUP.bed  hg19_repeatmasker.bed.gz  hg38_excluded.bed.gz      mm10_excluded.bed.gz
hg19_cytoband.bed         hg38_1000Genomes_DEL.bed  hg38_genes.bed.gz         mm10_genes.bed.gz
hg19_excluded.bed.gz      hg38_1000Genomes_DUP.bed  hg38_repeatmasker.bed.gz  mm10_repeatmasker.bed.gz
```

When you run `sv2 -hg19 ...` you can supply a full path to any faidx indexed fasta file. SV2 updates the config file in the install location every time you run this command

```
# location of the config file on my linux device
$ ls /lib/python2.7/site-packages/sv2/config/sv2.ini 
```
You can directly edit the config file, you might need su privileges to do this.
```
$ sudo vi /lib/python2.7/site-packages/sv2/config/sv2.ini 
``` 

```
[FASTA_PATHS]
hg19 = /home/atreus/fasta/human_g1k_v37.fasta
hg38 = None
mm10 = None

[INSTALL_DIR]
sv2_home = None

[RESOURCE_DIR]
sv2_resource = /home/atreus/ref/
```
`[FASTA_PATHS]` contain the full path to any samtools faidx indexed FASTA file

`[RESOURCE_DIR]` is the prefix to the download files 

If you need to install sv2 to a different path, this might help you out. https://stackoverflow.com/a/2916320/1459846

I hope this answers your question.

**Comment by holtgrewe** [comment]
Hi, I would be happy if I could give the path to the configuration INI file on the command line. Then, I could have one central installation of the data files and the configuration file which is independent from installing the package.

Would it be possible to add this feature?

Also, many other softwares use the program installation directory for default configuration and users then override the settings in `~/.local/<software>/settings-file-name` or similar locations.

E.g., see

- https://unix.stackexchange.com/questions/312988/understanding-home-configuration-file-locations-config-and-local-sha
