### ISSUE TITLE
Moving INFO/DENOVO_FILTER into FORMAT?

### ISSUE THREAD

**Issue by holtgrewe** [dantaki/SV2#11]
I am using SV2 on a large cohort (300 samples). In my current Delly2 pipeline, I create "cross cohort" VCF files, i.e.

- call variants in all samples
- merge variant files into a "cohort variation locus file"
- genotype all variants in each sample (one genotype file for each sample)
- merge all genotype files (simply paste the genotype columns of all files together with "bcftools merge")

For this, all sample-specific information has to go into the `FORMAT` rather than the `INFO` column of the resulting VCF files. It would be nice if the `INFO/DENOVO_FILTER` and maybe also the `FILTER` information could be written to the `FORMAT` rather than the `INFO` column, so this is easier.

**Comment by holtgrewe** [comment]
Alternatively, providing the different steps as individual commands (preprocessing, feature extraction, genotyping) would enable users to spread the time-consuming steps over a cluster and then perform a central re-genotyping step at the end with all feature files.

**Comment by dantaki** [comment]
The DENOVO filter considers REF and ALT genotype likelihoods for every sample in your cohort. It considers the median likelihood for each allele for the filter, thus if the filter is PASS, then all samples passed the filter.

Initially SV2 did split up the steps an individual commands. I can push a fix in the coming weeks. Thanks again for all your input and help.
