### ISSUE TITLE
Is SV2 suitable for plant genomes?

### ISSUE THREAD

**Issue by songtaogui** [dantaki/SV2#15]
Dear SV2 developer,

The tutorial of SV2 showed how to call SVs using Human WGS data, I was wondering that is SV2 suitable for SV calling in plant genomes?

Thank you!

best wishes!

Songtao Gui

**Comment by dantaki** [comment]
Not at the moment, I am working on a new fix that will allow users to specify exclude and FASTA files for their species. Note that the classifiers were trained on diploid organisms, so if your organism is not diploid there is no way for SV2 to work correctly.

**Comment by songtaogui** [comment]
Thanks for your reply. Looking forward to the new version of SV2.

Best wishes!


Danny Antaki <notifications@github.com> 于2018年6月17日周日 上午1:18写道：
