### ISSUE TITLE
Skipping bad entry

### ISSUE THREAD

**Issue by carleshf** [dantaki/SV2#19]
When running `sv2` I am getting a lot of these warnings (for `lumpy`, `strelka2`, and `manta`).

```
WARNING: Skipping bad entry chr22       50799940        .       C       T       .       LowEVS  SOMATIC;QSS=45;TQSS=2;NT=ref;QSS_NT=45;TQSS_NT=2;SGT=CC->CT;DP=78;MQ=48.15;MQ0=3;ReadPosRankSum=-1.07;SNVSB=0.00;SomaticEVS=4.31       DP:FDP:SDP:SUBDP:AU:CU:GU:TU    35:1:0:0:0,0:33,39:0,0:1,3      32:1:0:0:0,0:25,30:0,0:6,6 in VCF file .../strelka_C4_Fibroblast_chr/results/variants/somatic.snvs.vcf.gz. SV entry missing positions: https://github.com/dantaki/SV2/wiki/input#sv-input
```

Before running `sv2` I configured the same reference used to run `lumpy`, `strelka2`, and `manta`:

```
sv2 -download
sv2 -hg38 /media/NFS/ref/b38/Homo_sapiens_assembly38.fasta
```

 Why does it say that it is a bad entry and that there is *SV entry missing positions*?

The log suggests that `sv2` is skipping more than 273K SVs...

```
$ wc -l C4_Fibroblast_log
273020 C4_Fibroblast_log
```

---

I'm running `sv2` as:

```
sv2 -bam.../C4_bwa_b38_recal_leftalignindels.bam \
    -vcf.../C4_Fibroblast.svtyper.vcf .../manta_C4_fibroblast/results/variants/somaticSV.vcf.gz .../strelka_C4_Fibroblast_chr/results/variants/somatic.indels.vcf.gz .../strelka_C4_Fibroblast_chr/results/variants/somatic.snvs.vcf.gz \
    -snv .../C4_bwa_b38_gatk3_hc.vcf.gz \
    -g hg38 \
    -p C4.ped \
    -o C4_Fibroblast \
    -merge \
    -L C4_Fibroblast_log
```

**Comment by dantaki** [comment]
`-vcf` and `-bed` arguments are for SV calls. They have a specific format detailed in the wiki https://github.com/dantaki/SV2/wiki/input#sv-input

It appears this VCF entry is not formatted correctly.  SV<sup>2</sup> genotypes deletions and duplications. Not SNVs and not INDELs.
