### ISSUE TITLE
What about a bioconda package?

### ISSUE THREAD

**Issue by holtgrewe** [dantaki/SV2#2]
Hi, what about creating a [Bioconda](https://bioconda.github.io/index.html) package for this?

I can help but it looks like there are some files that don't exist locally but that are part of the download tarball.

Would you be interested in help with this?

**Comment by dantaki** [comment]
I was planning to put the source code on pypi but the source package is quite large (~250MB), which prevented that. 

Is there a limit on the size of the source package for Bioconda? If SV<sup>2</sup> will fit, I'll put it up there.

**Comment by holtgrewe** [comment]
Let's ask the Bioconda people:

https://github.com/bioconda/bioconda-recipes/issues/8144

**Comment by bgruening** [comment]
There is no size limit I'm aware of. However, the channel has a size limit. 250 should be ok in theory. In practice I would decouple the software from training-data/models and pull down those data during installation time.

Hope that helps,
Bjoern

**Comment by dantaki** [comment]
@bgruening Thanks Bjoern, can you guide me to a best practices guide for pulling down the data during install? Is it as simple as hosting the files somewhere and doing a `wget`?

**Comment by bgruening** [comment]
Sure. In conda you can create a post-link.sh/unlink.sh file that uses wget or similar to download data. For an example have a look at the biodonductor data packages: https://github.com/bioconda/bioconda-recipes/blob/0ef1235a96a28e0545c11f299311c13e5e9935a1/recipes/bioconductor-bsgenome.mmusculus.ucsc.mm9/post-link.sh (most of the file is for data-integrity checking)

**Comment by dantaki** [comment]
Thanks for all the help, I'll port SV<sup>2</sup> to bioconda within a few days.

**Comment by dantaki** [comment]
@holtgrewe I read up on contributing to bioconda and I don't have the current resources to do all that. However, I did upload a conda package here: https://anaconda.org/dantaki/sv2

If it's possible, feel free to push the conda package to bioconda. I would need some time to figure it out.

**Comment by bgruening** [comment]
@dantaki anything in particular what was complicated?

**Comment by dantaki** [comment]
@bgruening After I fork the bioconda repo do I perform this command 

```
git remote add upstream https://github.com/bioconda/bioconda-recipes.git
```

In the SV2 git repo? I think it's straightforward after that

**Comment by bgruening** [comment]
Mh, you don't need to add the remote afaik.

**Comment by holtgrewe** [comment]
Hi again, here is my first attempt at a Bioconda recipe:

https://github.com/bioconda/bioconda-recipes/pull/8240

However, the package is much too slow when compared to the >200MB download of the SV2 v1.4.0 release...

@dantaki I would be willing to invest some time into building a SV2 bioconda package but I would need your help with it ;) Are you interested?

**Comment by dantaki** [comment]
Sure, is the download/build too slow for v1.4.1 or the actual execution of SV2 too slow? 

My bandwidth is limited at this time, but I will be glad to help. Much appreciated! 

Also, sorry for the naive question, what is the benefit of having a conda install vs a pip install?
