### ISSUE TITLE
strelka2 compatibility

### ISSUE THREAD

**Issue by carleshf** [dantaki/SV2#20]
Is there any way to include the results from `strelka2` as merging breakpoints joint to `lumpy` and `manta` files?

**Comment by dantaki** [comment]
SV<sup>2</sup> is a structural variant (>50bp) genotyper specific to germline variants. I do not recommend genotyping somatic variants with this tool. However, SV<sup>2</sup> can genotype variants given they are formatted correctly, https://github.com/dantaki/SV2/wiki/input#sv-input

For example, an INDEL

VCF: 
```
chr1    100    .    ATGCAT    A  .    .    SVTYPE=DEL;END=105; ....  
```

BED:

```
chr1 99    105    DEL
````


INDELs that are informative by CIGAR string (they do not have discordant paired-end or split-read features) would not genotype well with SV<sup>2</sup>
