### ISSUE TITLE
Preprocessing with read_count==0 and time-consuming problem

### ISSUE THREAD

**Issue by LuQiao-spec** [dantaki/SV2#23]
Hi Danny,

I used SV2 to test real patients' data by the following command:
sv2 -i /path/to/sample.cram -v /manta/path/to/sample/results/variants/candidateSV.vcf.gz -p /path/to/sample.ped -snv /path/to/sample.snv.vcf.gz -O /output/path -o sample -genome hg38
1. There are ~150,000 SVs from manta to be genotyped. The coverage is ~30X. But it takes more than 2 days to finish preprocess and extract feature. Also this running didn't include genotyping process. Is there reasons to explain the time-consuming problem?
sv2 version:1.4.3.4    report bugs to <dantaki at ucsd dot edu>       error messages located in STDOUT
************************************************
 PREPROCESSING COMPLETE <time elapsed: 2:30:25>
************************************************
*************************************************************
 FEATURE EXTRACTION COMPLETE <time elapsed: 2 days, 1:47:58>
*************************************************************
2. In the preprocessing step, only chr. 1 could be recorded for its median coverage, insert size, read length. The other chromosomes are recorded as 0, but with snv depth. I checked Preprocess.pyx, it's because: if read_count == 0: out.write('\t'.join(map(str,(Bam.id,chrom,'0','0','0','0',chr_size,snv_depth[chrom][0],snv_depth[chrom][1])))+'\n'). But for our real data, is this weird to get such result? It has affected the downstream steps, features and genotyping. I can only get the a part of genotyped SVs on chr1. All other SVs are didn't genotyped, and labeled as ./. Is there something wrong with my input files?

#id     chrom   coverage_median read_length_median      insert_size_median      insert_size_mad bam_bp_parsed   snv_depth_median        snv_parsed
sample      chr1    38.29   151.0   343.0   94.885  8140204 34.0    3554301
sample      chr2    0       0       0       0       8742321 34.0    3876220
sample      chr3    0       0       0       0       9365911 34.0    3272803
sample      chr4    0       0       0       0       9114963 35.0    3216810
sample      chr5    0       0       0       0       8840577 34.0    2963697
sample      chr6    0       0       0       0       9083885 34.0    2877283
sample      chr7    0       0       0       0       8501055 34.0    2492951
sample      chr8    0       0       0       0       8981936 34.0    2545109
sample      chr9    0       0       0       0       7045033 34.0    1929229
sample      chr10   0       0       0       0       9310107 34.0    2164750
sample      chr11   0       0       0       0       8589126 34.0    2173292
sample      chr12   0       0       0       0       8512410 34.0    2143964
sample      chr13   0       0       0       0       8538945 35.0    1583211
sample      chr14   0       0       0       0       7803056 34.0    1491732
sample      chr15   0       0       0       0       6341254 34.0    1269410
sample      chr16   0       0       0       0       7438127 34.0    1370467
sample      chr17   0       0       0       0       8196419 33.0    1222043
sample      chr18   0       0       0       0       8217218 35.0    1253336
sample      chr19   0       0       0       0       7757229 33.0    974316
sample      chr20   0       0       0       0       8556321 34.0    999899
sample      chr21   0       0       0       0       6759962 34.0    579713
sample      chr22   0       0       0       0       5109515 33.0    567518
sample      chrX    0       0       0       0       7943393 17.0    1871744
sample      chrY    0       0       0       0       2278184 0       0
sample     GENOME  38.29   151.0   343.0   94.885  8140204 34.0    46393798
         
3. Can we separate three step to run? 

Thanks!

**Comment by dantaki** [comment]
For 30x data it shouldn't take this long to run. Are you running sv2 locally or on a server? The preprocessing file indicates that you have data for the genome with SNVs but not in your BAM. Does your BAM file only have chr1 in it?

**Comment by LuQiao-spec** [comment]
Thanks Danny for your reply. I run the SV2 on server and the BAM file has whole genome. I guess it's because I set h_vmem=2G, it's too small to run completely. When I set the h_vmem = 30G, there's no error. But it's still need >7h. Does the h_vmem really affect the error? What's the memory of SV2 when there are 30x coverage and 1e5 SVs?
************************************************
 PREPROCESSING COMPLETE <time elapsed: 0:34:10>
************************************************
*****************************************************
 FEATURE EXTRACTION COMPLETE <time elapsed: 6:00:25>
*****************************************************
*********************************************
 GENOTYPING COMPLETE <time elapsed: 7:32:22>
*********************************************

**Comment by dantaki** [comment]
If you are experiencing longer wall times, I would recommend splitting up your SV call set into batches of 10,000 SVs. Also longer SVs will take more time to processes.
