### ISSUE TITLE
de novo

### ISSUE THREAD

**Issue by callaL** [dantaki/SV2#29]
（1） Can this software do de novo analysis? Can the author provide an example if possible?
（2）The author mentioned standard filtering and de novo filtering in the software description. What are the two specific filtering conditions? Or in other words, which indicators are filtered by both filters?

**Comment by dantaki** [comment]
1. It's unclear what you mean specifically by de novo analysis. If you mean will SV2 provide a list of de novo mutations, the answer is no. However, SV2 will genotype SVs and provide filters for de novo mutation detection. So you can write a script to parse the genotype information and find variants where the child is `0/1` and the parents are both `0/0` for variants with `DENOVO_FILTER=PASS` in the `INFO` column.

2. The two specific filtering conditions are detailed in the second paragraph of the "performance results" section https://academic.oup.com/bioinformatics/article/34/10/1774/4781690#118448321 and in supplementary table s4
