### ISSUE TITLE
Test data run

### ISSUE THREAD

**Issue by fritzsedlazeck** [dantaki/SV2#3]
Hi,
we tried to run the test data that you provide with hg19 using the commands that you suggest.

All of the variance in the resulting file show GENOTYPEFAIL. I have checked for differences in the chr names, but they appear to be the same. 

Do you have any advice?
Thanks
Fritz

**Comment by dantaki** [comment]
The BAM file is severely downsampled. The tutorial is merely an example on how to run SV<sup>2</sup>, not an example of genotype scoring or filtering. 

In the tutorial wiki page it states

Note: This tutorial is merely an example. The BAM file has been down-sampled to low depths (<1x) inadequate for genotyping.

I hope this answers your question.

**Comment by fritzsedlazeck** [comment]
thanks.
Fritz
